version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - ${APP_PORT}:80
        volumes:
            - ${APP_DIR}:/code
            - ./container/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - server
        depends_on:
            - php
    
    php:
        build: ./container/php
        volumes:
            - ${APP_DIR}:/code
            - ./container/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - database
            - server
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - data:/var/lib/mysql
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80
        networks:
            - database
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql

volumes:
    data:

networks:
    server:
        driver: bridge
    database:
        driver: bridge
